### ISSUE TITLE
Make an option to call role more than once

### ISSUE THREAD

**Issue by guka90** [Darker/auto-client#1]
It seems not possible to call your role when you enter first in lobby because others can't see what you wrote before they enter lobby.

This could be fixed by letting your tool write more than once (three times - then you get chat blocked) AND adding a small delay between messages (could be customizable for better results).

Nevertheless, everything is working fine! Thank you for your effort!

**Comment by Darker** [comment]
I already had something like this mind. I think I'll go the more complicated way and implement simple scripting language for call text(s). Specifically something like:

     $>"mid";%200;"mid";%1200

Where `%` indicates sleep, quotes indicate call message.

**Comment by Darker** [comment]
@guka90  I will close this when I actually implement the feature. Once again, thanks for contributing.

**Comment by Darker** [comment]
@guka90 Hello. Just wanted to say that this was finally, sort of, implemented.

The documentation: https://github.com/Darker/auto-client/wiki/Auto-call-scripts
Somewhat stable version that uses it: https://github.com/Darker/auto-client/releases/tag/v3.7-beta
