### ISSUE TITLE
WindowsAccessDeniedException

### ISSUE THREAD

**Issue by iCornflakes** [Darker/auto-client#10]
http://prntscr.com/84q6h5 on try to use auto launch

Windows 10 Home 64-Bit
Java 8u51

**Comment by Darker** [comment]
This has happened because PVP.net Client is running under Administrator privilegies. In that case, operating system protects the Client from access.

To allow AutoClient to work, you need to run it as Administrator or run PVP.net Client under normal privilegies.

**Comment by iCornflakes** [comment]
Ah okey, thank you very much c:

**Comment by Darker** [comment]
Ok, I consider this solved.
