### ISSUE TITLE
Some Requests and Bugs

### ISSUE THREAD

**Issue by CakeRage** [Darker/auto-client#14]
Bugs:
-Sometimes it searches for the champion but doesn't select it
-Sometimes it doesn't call our your lane in the chat

Requests:
-Put an option to select which one should have priority, champion select or lane call

Awesome client you've made, it works really well. Thank you so much for the work you put into this and releasing it to the public for free! I've told all my friends about this and they all love it. <3

**Comment by Darker** [comment]
I experience the same problems as you do, but don't know what exactly causes them. I will add the priority option, that's a good idea!

Btw I also have slightly newer version that is more reliable. I will try to release it soon.

**Comment by Darker** [comment]
New version was released, check if it still happens.
