### ISSUE TITLE
UMD Research Study

### ISSUE THREAD

**Issue by UMD-study** [Darker/auto-client#15]
Hi there,
We are researchers from the University of Maryland conducting a study about software code reuse. If you are interested in helping us in this study​ through ​a short interview about this project, please contact us on ​software-reuse-study@cs.umd.edu​ for more information​. You will be ​compensated for your time.

Thanks
Ahmed

**Comment by Darker** [comment]
Hello Ahmed.
I will gladly participate in an interview. However I was unable to verify, whether your study is real or not, therefore I will be using disposable mailbox darker_auto_client@grr.la to contact you, It might fall in your spam folder.
Have a nice day,
Jakub
