### ISSUE TITLE
The Auto Accepting tool is broken.

### ISSUE THREAD

**Issue by ViktoRRRRRRRRRR** [Darker/auto-client#19]
When i activate the program it clicks where the accept button should be without any accept nutton. Im on windows xp. Btw THE PROGRAM IS AMAZING SO KEEP THE GREAT WORK AND FIX THE LITTLE BUGS :D

**Comment by Darker** [comment]
@ViktoRRRRRRRRRR  Does it still happen? If it does, could you provide a screenshot of the problem? Do not forget to erase personal information from any screenshots!

**Comment by Darker** [comment]
Time out.
