### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by ciole133** [Darker/auto-client#21]
Hi. After installing AutoClient my League Of Legends Login Error pops up immediatly without any MS, cant do anything. Any fix please ? Tried everything, Clock settings, firewall, internet explorer advanced tab, DNS server 8.8.8.8 and 8.8.4.4...

**Comment by Darker** [comment]
AutoClient does not interfere with network in any way. The error you're getting is probably (like almost 100%) not related to it. Try login to different servers or re-instal client, it might help.

But do note that this is AutoClient support page, not PVP.net client support page.

**Comment by Darker** [comment]
Closing because no reply was received.
