### ISSUE TITLE
java.class.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Drigtime** [Darker/auto-client#22]
Hi I have a problem with the auto client when I try to enable the auto login or the auto queue I have this error message.
 
`<a href="http://www.noelshack.com/2016-36-1473494041-capture.png"><img src="http://image.noelshack.com/minis/2016/36/1473494041-capture.png" border="0" alt="1473494041-capture.png - envoi d'image avec NoelShack" title="1473494041-capture.png"/></a>

**Comment by Darker** [comment]
Hello, that's a strange error. It seems like the archive is corrupted and a part of the program is missing. Where did you download it from?

**Comment by Drigtime** [comment]
I downloaded it from github on the releases page

**Comment by Drigtime** [comment]
I fix it. I uninstalled all java's version I has and re-installed java and it worked

**Comment by Darker** [comment]
Ok, closing then.
