### ISSUE TITLE
Auto login seems to be non-working

### ISSUE THREAD

**Issue by sarpik** [Darker/auto-client#32]
https://imgur.com/PgIkyZN

I've checked FAQ, how to use etc. it doesn't help, client is NOT minimized, if you need more information please contact me via email: *///email deleted for your own protection ///*

**Comment by HurricanKai** [comment]
In the New Client This is not Yet Supported!

**Comment by Darker** [comment]
It should work but is extremely unreliable. I didn't have time to improve it.

**Comment by OrangutanGaming** [comment]
Haven't been working at all for me

**Comment by OrangutanGaming** [comment]
My version: ![image](https://user-images.githubusercontent.com/18350092/35231480-d560f7da-ff90-11e7-80a1-b90cf987de2c.png)
