### ISSUE TITLE
Why Slow-Type?

### ISSUE THREAD

**Issue by HurricanKai** [Darker/auto-client#35]
Why not just putting an 
```
string towrite = "jungle"
foreach (char c in towrite)
{
    write(c);
}
```
or
```
copytoclipboard(towrite);
pasteclipboard();
```

NOTE: this is semi-code for C# no idea how it is in Java, but in C# it woud be possible, and Asking doesnt Costs anything, i hope.

**Comment by Darker** [comment]
The former just wouldn't work, I need to do some processing with the letters. And it didn't work without delay. Back in the days of old client, simple for loop was possible but not any more.

The latter is a good idea and I wanted to do it but didn't gave time just yet.
