### ISSUE TITLE
No Auto-Update For Champions

### ISSUE THREAD

**Issue by HurricanKai** [Darker/auto-client#36]
Get the Champions into an Array/List using the Riot API

(there are other APIs for getting that basic stuff if you dont like the Offical one!)

btw. I dont know if this Project is Left, or not, But ill try.

Please answer if this isnt Closed.

**Comment by Darker** [comment]
The update isn't automatic yet, but can be forced by deleting the `lol_resources` folder which will force re-download of resources. As described in this short video: https://www.youtube.com/watch?v=m4BHVCcCyRM
