### ISSUE TITLE
AutoClient

### ISSUE THREAD

**Issue by xM4st3r** [Darker/auto-client#7]
Hi ! 

Just when i'm in champs select , the bot didn't write anything just select the champ.

**Comment by Darker** [comment]
Does this happen allways or just sometimes at random? Yesterday night, a hotfix was released, did you try it?

**Comment by xM4st3r** [comment]
#fail just write but didn't press enter and directly go choose spell

**Comment by Darker** [comment]
Hi.
Unless I can reproduce these problems on my computer, I can't find a reason why do they happen. If you have any idea what the problem is, or how to make it happen, just tell me.
Also remember that tonight, the program was updated.

**Comment by xM4st3r** [comment]
i also updated the program but i think my computeur is too slow so need double click for write anything xD

**Comment by Darker** [comment]
Hello again. I am sorry, I forgot to upload the update. Try again: https://github.com/Darker/auto-client/raw/master/release/AutoClient_stable.zip

Also, you can watch the [release folder](https://github.com/Darker/auto-client/raw/master/release) to see when were the archive files changed.

**Comment by xM4st3r** [comment]
Thanks for the update  ! Now work perfect :D

**Comment by Darker** [comment]
I am glad to hear that!
